apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-app-template
  name: devops-app-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app-template
  template:
    metadata:
      labels:
        app: devops-app-template
    spec:
      containers:
        - image: 029492911530.dkr.ecr.eu-central-1.amazonaws.com/devops-app-template:version-1.1
          name: devops-app-template
          ports:
          - containerPort: 4002

---

apiVersion: v1
kind: Service
metadata:
  name: devops-app-template-service
spec:
  type: LoadBalancer
  selector:
    app: devops-app-template
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002